### ISSUE TITLE
[Major] HQM Bugged in 1.1.15 for old worlds

### ISSUE THREAD

**Issue by SnowShock35** [SnowShock35/Obscurity#159]
@johnnymobbins We need to revert to HQM 1.1.14 and redo the changes but with more testing and caution with previous worlds. No major changes please.

**Comment by johnnymobbins** [comment]
The issue was the change of the 1st quest. It was changed to a location quest. I have tested all other changes in that version and they all work fine in both 1.1.14 and 1.1.15. 

I guess if the location based quest change create issues with previous saves. I will not make any more  quest changes of that nature again.

**Comment by LyraelRayne** [comment]
IT could also be the fact that the very first quest (upon which every single other quest depends) was the one that got changed.  Could also be an instance of https://bitbucket.org/Newcastlegeek/hqm-bugtracker/issues/186/server-crash-when-updating-remaking-quests or https://bitbucket.org/Newcastlegeek/hqm-bugtracker/issues/101/updating-hqm-questhqm-stops-server-from (or both)

**Comment by LyraelRayne** [comment]
http://forum.feed-the-beast.com/threads/1-7-10-the-ferret-business-wip-hqm-400-quests-v-0-1-0.64930/page-65#post-1210976 <--- looks like the ferret business also had a similar issue.
