### ISSUE TITLE
Spruce Sapling growth

### ISSUE THREAD

**Issue by SudzBud** [SnowShock35/Obscurity#222]
I was able to grow spruce trees on one of the earlier builds, but the latest release will no longer grow saplings into trees for me. If I bone meal the sapling, I see in waila that it sometimes reports as an oak sapling and then back to a spruce. I am thinking that when it reports as oak is when the tick would have triggered growth.
All other saplings seems ok so far. Acacia, jungle, and oak. I am retrying birch now.

**Comment by SudzBud** [comment]
Birch, Dark Oak, Silverwood, and greatwood all grow normally. Issue seems to only affect Spruce.

**Comment by AKTheKnight** [comment]
@SnowShock35 hmm. FIX IT

**Comment by LyraelRayne** [comment]
I just grew spruce both using bone meal in the dark and by waiting at an appropriate light level.

Can you put up a screenshot of the area you're trying to grow in? Spruce tends to be a tad taller than other trees so if you have an obstruction such as a roof then it might not grow.

**Comment by SudzBud** [comment]
Silverwood, Dark Oak, and Great wood trees all grew in the same spot. I am pretty sure all of these are much larger than spruce. The location is on the "surface" of deep dark.

**Comment by LyraelRayne** [comment]
Those trees are also known for breaking through the ceilings of the "indestructible" compact machines. i.e. they don't really follow Vanilla growth mechanics. Of the vanilla trees, Spruce is the one I always had the most trouble with obstruction.

Another dumb question: Have you tried a different spot on the surface? Also have you altered anything at all about the pack? (Config, extra mods, etc.? ) I only ask because I can quite reliably grow spruce in a location just like the one you described. Which means either your copy of the pack is different to mine or there's something about that specific spot.

I did notice the Waila saying it's an "oak" sapling but I suspect that's a Waila bug. When the tree grew, it was definitely producing spruce wood. And although the leaves said they were oak leaves, the saplings dropped were definitely Spruce.

**Comment by SudzBud** [comment]
The thing is I was able to grow spruce early on in my game. I think it stopped after one of the updates. I am checking now to see if I added anything to the pack. Perhaps backup? Will get back on that.

**Comment by SudzBud** [comment]
The only mod I would have added via the curse client would be aroma backup, but I see it already in a list of mods included. I am pretty certain I didn't add anything else as I think it would break the intended progression. I am going to backup, delete and re-install the pack, creative test, then restore backup and retry. I will report after these tests.

**Comment by LyraelRayne** [comment]
Thanks. Would be good to rule that out. 

Were you able to grow spruce earlier in the game in that particular spot? Also, just as a thought. Are there any of those arcane lamps from Thaumcraft about? Those things place random "light" blocks around the joint which might possibly interfere with plant growth. You can usually find them and break them though.

**Comment by SudzBud** [comment]
woot! remove and re-add fixed issue. Not sure how it had corrupted just spruce, but it works now. Seems to take quite a lot of bone meal to get growth, but it grows. Haven't tried with watering cans. I previously had tried multiple stacks of meal, was able to get growth now with only half stack. Seems a little high, but I'll take it. May be hard to get feeding the masses quest for spruce or however it is named. Thanks for the effort in looking into it.
