### ISSUE TITLE
Can't complete quest

### ISSUE THREAD

**Issue by Minarch** [SnowShock35/Obscurity#229]
Hi there.
Im playing on a multiplayer Regrowth-server and we're in a party.
My mate completed a quest and I can't Claim Reward on certain quests.
I tried spawning the OP edition and reset, but I still can't claim reward.

The mods-folder contain the file HQM-The Journey-4.4.4.jar, in case you need a version.

**Comment by LyraelRayne** [comment]
Hi there Minarch. First of all, this is the issue tracker for Obscurity, not Regrowth or HQM. You might find more useful help at https://github.com/lorddusk/HQM/issues (as this looks more like a HQM thing) or https://github.com/thephoenixlodge/Regrowth-Stuff/issues (I *think* this is where you go for Regrowth issues).

Having said that, often we've found that when a quest can't be completed in Obscurity, it's because there simply isn't enough space in the player's inventory for the reward. Ask your friend to try dumping all their stuff into a chest before claiming the reward. This is especially an issue with quests that give a number of non stacking items because they take up a lot of slots. 

I'm going to close this as there isn't a lot we can do here at Obscurity if it is an actual bug with HQM or Regrowth. If the above doesn't fix it, create a new issue at one/both of the HQM/Regrowth issue trackers..
